export default {
    MARK_NOTIFICATION_READED: 'MARK_NOTIFICATION_READED',
    MARK_ALL_NOTIFICATIONS_READED: 'MARK_ALL_NOTIFICATIONS_READED',
    START_NOTIFICATION_REQUEST: 'START_NOTIFICATION_REQUEST',  //加了这些，后期业务中加isLoading等的时候用
    FINISH_NOTIFICATION_RESPONSE: 'FINISH_NOTIFICATION_RESPONSE',
    RECEIVED_NOTIFICATIONS:'RECEIVED_NOTIFICATIONS',
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',

}